### ISSUE TITLE
Activity 是什么呢？

### ISSUE THREAD

**Issue by pokercc** [li-xiaojun/MVPSample#1]
那这个activity是什么呢？

**Comment by dance609195946** [comment]
Activity是充当模块容器，有的人会将Activity和Fragment充当Presenter

**Comment by pokercc** [comment]
有的时候，业务逻辑和activity的生命周期函数有关系，比如记录操作时间，这个情况下，activity 或者是fragment也起着很重要的作用，那么好像不是容器呢，是一个触发还是什么呢？

**Comment by dance609195946** [comment]
对于生命周期的处理，让Presneter定义对应各个生命周期的方法，然后去调用，Activity仍然充当容器

**Comment by pokercc** [comment]
俊哥，我今天看了react flux，发现activity好像可以认为是触发action的地方，那么你写的这个demo很像前端的react flux应用架构，不知道我说的对不对。
